AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'

AlignParameters:
  EnforcedStyle: with_fixed_indentation

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 160

MethodLength:
  Enabled: true
  CountComments: false
  Max: 20

Metrics/AbcSize:
  Enabled: false

CyclomaticComplexity:
  Max: 10

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
